### ISSUE TITLE
delegatorState is missing for a specific delegator

### ISSUE THREAD

**Issue by ioannist** [OAK-Foundation/OAK-blockchain#214]
parachainStaking.topDelegations for a specific collator, returns a set of delegators
parachainStaking.delegatorState for 1 of these delegators, returns Unknown
This issue happens only for a specific delegator.

block
0x2979563cd3619ef7307005ff7bd1bd0230533d93b56087bcc04ac662edf4bf6c

collator: 684xNMHJrNNqVT26AB19mPApS2FRAMVspkgALq7WgBAvohho
```
parachainStaking.topDelegations: Option<PalletParachainStakingDelegations>
{
  delegations: [
    {
      owner: 69ZNQdLopee2ZNDL5xkSKu9QpkQq7jJGgiw9tFjDZVtoLRim
      amount: 1,179,800,000,000,000
    }
    {
      owner: 6AMsXyV1CYc3LMTk155JTDGEzbgVPvsX9aXp7VXz9heC3iuP
      amount: 14,500,000,000,000
    }
    {
      owner: 6BDaap5XLPtgkkkWCBXPzaiRG5BL29E7RMnpGJ685Y4hvvq9
      amount: 12,450,000,000,000
    }
    {
      owner: 67AHmcoC8Rp68b5SzDhf5fpzHmRTAcuEctvciPDEyiA57ons
      amount: 12,170,000,000,000
    }
    {
      owner: 69BMX8xZaWevFhDssG3RiqqDyzrx5uQgVo9XztV5VjMNimr8
      amount: 11,190,000,000,000
    }
    {
      owner: 681wSDNULDV3pduPvWgLxKMvGc3pgiwCimp1dRr9qVtSrfk1
      amount: 10,000,000,000,000
    }
    {
      owner: 6Bu7uoHFwGELfVAxtepJa8xgCevVjtsVdK4nLqnDWEJpPm2E
      amount: 5,110,000,000,000
    }
    {
      owner: 66XWAcwQHXccJcFFY2raBGSzM6EVdCFKiJ5HjEYN7uq5CKq9
      amount: 5,000,000,000,000
    }
    {
      owner: 69mcbb4o9DZCe9hQFxC5jcoHRcZb2ffVeJ14tdqTMTZ7W4E2
      amount: 4,200,000,000,000
    }
    {
      owner: 68sdNVNYXGyrtmiahL2C9v8CfyhjBonpPaeSsgLuS9CEzSmL
      amount: 2,601,204,399,877
    }
    {
      owner: 67kgfmY6zpw1PRYpj3D5RtkzVZnVvn49XHGyR4v9MEsRRyet
      amount: 1,200,000,000,000
    }
    {
      owner: 66ZfMmWxtPXpnY5Rmj9LmzNjVN2veVyzdAqLjrvJiqdxqsS1
      amount: 1,180,000,000,000
    }
    {
      owner: 6BagJrpC13DX6NWJYNqvcaPrgAtfm4L3zf2ZJb8LwBd2y1hK
      amount: 1,100,000,000,000
    }
    {
      owner: 69vGFK17eUH8WjbLs8F59J958Ra6tB1gAiaHEk7JL5mtX8r4
      amount: 1,000,000,000,000
    }
    {
      owner: 679zFkKB2TMwVD7kcQhR7NM8oM2sSenJ5ZTWu91CAt3PF8px
      amount: 840,000,000,000
    }
    {
      owner: 69TJrMGnkqqzyLP2XDK86wRrEnUrKUA7FVbvwM5xemr58uHt
      amount: 510,000,000,000
    }
    {
      owner: 68jM33DoSS7QsYfa75oRizbcyTHs28urFCmWQaEkwZ1QSHPd
      amount: 500,000,000,000
    }
    {
      owner: 6B7ACD3jQPuC2TBC55K7QTedy82TgVGP5H72DyRigkXdkieD
      amount: 500,000,000,000
    }
  ]
  total: 1,263,851,204,399,877
}
```

delegator:
68jM33DoSS7QsYfa75oRizbcyTHs28urFCmWQaEkwZ1QSHPd
```
parachainStaking.delegatorState: Option<PalletParachainStakingDelegator>
<unknown>
```

**Comment by nvengal** [comment]
This delegator's state is not missing, but it looks like we're having trouble serializing it.
When the state is missing the response is : `<none>`
When using the polkadot.js sdk to directly query this state we see the underlying error:
```
Error: Unable to decode storage parachainStaking.delegatorState: entry 0:: createType(PalletParachainStakingDelegator):: decodeU8a: failed at 0x01d9020000… on status (index 4/5): {"_enum":{"Active":0}}:: Unable to create Enum via index 1, in Active
    at ja._newType (https://polkadot.js.org/apps/polkadot.01.9f1fd14a.js:1:77007)
    at ja._formatStorageSetEntry (https://polkadot.js.org/apps/polkadot.01.9f1fd14a.js:1:76528)
...
```

Looks like this issue is fixed here by moonbeam: https://github.com/PureStake/moonbeam/pull/1702

We will pull this update into our next runtime upgrade.

**Comment by irsal** [comment]
should be patched with this realease https://github.com/OAK-Foundation/OAK-blockchain/releases/tag/v1.6.0

**Comment by nvengal** [comment]
Verified that chain state is now serializable for the affected delegator
```
parachainStaking.delegatorState: Option<PalletParachainStakingDelegator>
{
  id: 68jM33DoSS7QsYfa75oRizbcyTHs28urFCmWQaEkwZ1QSHPd
  delegations: [
    {
      owner: 684xNMHJrNNqVT26AB19mPApS2FRAMVspkgALq7WgBAvohho
      amount: 500,000,000,000
    }
  ]
  total: 500,000,000,000
  lessTotal: 500,000,000,000
  status: {
    Leaving: 729
  }
}
```
